# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 15:26
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name=b'address')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name=b'location')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'bus stop',
                'verbose_name_plural': 'bus stops',
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BusStop', verbose_name=b'bus stop')),
            ],
            options={
                'verbose_name': 'favourite bus stop',
                'verbose_name_plural': 'favourite bus stops',
            },
        ),
        migrations.RemoveField(
            model_name='friendgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='friendgroup',
            name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='userfriendgroup',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='userfriendgroup',
            name='friend_group',
        ),
        migrations.RemoveField(
            model_name='userfriendgroup',
            name='member',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username'),
        ),
        migrations.DeleteModel(
            name='FriendGroup',
        ),
        migrations.DeleteModel(
            name='UserFriendGroup',
        ),
        migrations.AddField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'user'),
        ),
        migrations.AddField(
            model_name='busstop',
            name='favourites',
            field=models.ManyToManyField(through='app.Favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=set([('user', 'stop')]),
        ),
    ]
