# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_busstop_favourites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='user',
            new_name='favourite',
        ),
        migrations.AddField(
            model_name='busstop',
            name='favourites',
            field=models.ManyToManyField(through='app.Favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=set([('favourite', 'stop')]),
        ),
    ]
